# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.core.validators
import django.utils.timezone
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre del evento", max_length=200),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Descripción detallada del evento"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(help_text="Fecha y hora de inicio del evento"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(help_text="Fecha y hora de fin del evento"),
                ),
                (
                    "lugar",
                    models.CharField(
                        help_text="Lugar donde se realizará el evento", max_length=200
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, help_text="Dirección completa del evento"
                    ),
                ),
                (
                    "cupo_maximo",
                    models.PositiveIntegerField(
                        help_text="Número máximo de participantes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Costo de inscripción al evento",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "imagen_banner",
                    models.ImageField(
                        blank=True,
                        help_text="Banner promocional (JPG/PNG, máx 2MB, recomendado 1200x400px)",
                        null=True,
                        upload_to="eventos/banners/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            eventos.models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADO", "Publicado"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        help_text="Estado actual del evento",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de creación del evento",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última modificación"
                    ),
                ),
                (
                    "requiere_aprobacion",
                    models.BooleanField(
                        default=False,
                        help_text="¿Las inscripciones requieren aprobación?",
                    ),
                ),
                (
                    "porcentaje_asistencia_minimo",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Porcentaje mínimo de asistencia para certificado",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "genera_certificado",
                    models.BooleanField(
                        default=True, help_text="¿Este evento genera certificado?"
                    ),
                ),
                (
                    "numero_sesiones",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número de sesiones del evento",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCambioEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_modificado", models.CharField(max_length=50)),
                ("valor_anterior", models.TextField()),
                ("valor_nuevo", models.TextField()),
                (
                    "fecha_cambio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Historial de Cambio de Evento",
                "verbose_name_plural": "Historial de Cambios de Eventos",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("ACADEMICO", "Académico"),
                            ("CULTURAL", "Cultural"),
                            ("CORPORATIVO", "Corporativo"),
                            ("DEPORTIVO", "Deportivo"),
                            ("SOCIAL", "Social"),
                        ],
                        help_text="Tipo de evento",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción del tipo de evento"
                    ),
                ),
                (
                    "color_badge",
                    models.CharField(
                        default="#6c757d",
                        help_text="Color para el badge en hexadecimal (ej: #007bff)",
                        max_length=7,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos de Eventos",
                "ordering": ["nombre"],
            },
        ),
    ]
