# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó el evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que modificó el evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcambioevento",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_cambios",
                to="eventos.evento",
            ),
        ),
        migrations.AddField(
            model_name="historialcambioevento",
            name="modificado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tipo_evento",
            field=models.ForeignKey(
                help_text="Tipo de evento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="eventos.tipoevento",
            ),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(fields=["estado"], name="eventos_eve_estado_6b5412_idx"),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(
                fields=["fecha_inicio"], name="eventos_eve_fecha_i_0df3d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(
                fields=["tipo_evento"], name="eventos_eve_tipo_ev_364473_idx"
            ),
        ),
    ]
