# Generated by Django 5.2.7 on 2025-11-17 14:11

import certificados.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_verificacion",
                    models.CharField(
                        default=certificados.models.generar_codigo_verificacion,
                        help_text="Código único de verificación",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Archivo PDF del certificado",
                        null=True,
                        upload_to="certificados/%Y/%m/",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de generación del certificado",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de envío por correo", null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("GENERADO", "Generado"),
                            ("ENVIADO", "Enviado"),
                            ("ERROR", "Error"),
                        ],
                        default="GENERADO",
                        help_text="Estado del certificado",
                        max_length=20,
                    ),
                ),
                (
                    "intentos_envio",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de intentos de envío"
                    ),
                ),
                (
                    "error_envio",
                    models.TextField(
                        blank=True, help_text="Descripción del error en el envío"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="PlantillaCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la plantilla", max_length=100
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción de la plantilla"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo institucional para el certificado",
                        null=True,
                        upload_to="certificados/logos/",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=False, help_text="¿Esta plantilla está activa?"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#2c3e50",
                        help_text="Color primario en hexadecimal",
                        max_length=7,
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#34495e",
                        help_text="Color secundario en hexadecimal",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Certificado",
                "verbose_name_plural": "Plantillas de Certificados",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
