# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificados", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillacertificado",
            name="creada_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="certificado",
            index=models.Index(
                fields=["codigo_verificacion"], name="certificado_codigo__db2fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificado",
            index=models.Index(fields=["estado"], name="certificado_estado_02805c_idx"),
        ),
    ]
