# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre identificador de la plantilla", max_length=100
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        help_text="Asunto del correo (acepta variables)", max_length=200
                    ),
                ),
                (
                    "cuerpo_texto",
                    models.TextField(
                        help_text="Cuerpo del correo en texto plano (acepta variables)"
                    ),
                ),
                (
                    "cuerpo_html",
                    models.TextField(
                        blank=True,
                        help_text="Cuerpo del correo en HTML (opcional, acepta variables)",
                    ),
                ),
                (
                    "pie_pagina",
                    models.TextField(blank=True, help_text="Pie de página del correo"),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=False, help_text="¿Esta plantilla está activa?"
                    ),
                ),
                (
                    "predeterminada",
                    models.BooleanField(
                        default=False,
                        help_text="¿Es la plantilla predeterminada del sistema?",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "variables_disponibles",
                    models.TextField(
                        default="{{nombre}}, {{evento}}, {{fecha}}, {{hora}}, {{lugar}}, {{codigo_qr}}",
                        help_text="Variables disponibles para usar en la plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Correo",
                "verbose_name_plural": "Plantillas de Correo",
                "ordering": ["tipo_notificacion", "-activa", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("CONFIRMACION_INSCRIPCION", "Confirmación de Inscripción"),
                            ("RECORDATORIO_EVENTO", "Recordatorio de Evento"),
                            ("CAMBIO_EVENTO", "Cambio en Evento"),
                            ("CANCELACION_EVENTO", "Cancelación de Evento"),
                            ("CERTIFICADO_DISPONIBLE", "Certificado Disponible"),
                            ("PAGO_CONFIRMADO", "Confirmación de Pago"),
                            ("INSCRIPCION_APROBADA", "Inscripción Aprobada"),
                            ("INSCRIPCION_RECHAZADA", "Inscripción Rechazada"),
                        ],
                        help_text="Código identificador del tipo",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre descriptivo", max_length=100),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción del tipo de notificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="¿Este tipo está activo?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Notificación",
                "verbose_name_plural": "Tipos de Notificaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionRecordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="¿Los recordatorios están activos?"
                    ),
                ),
                (
                    "horas_antes",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Horas antes del evento para enviar recordatorio",
                    ),
                ),
                (
                    "mensaje_personalizado",
                    models.TextField(
                        blank=True, help_text="Mensaje adicional para el recordatorio"
                    ),
                ),
                (
                    "enviado",
                    models.BooleanField(
                        default=False, help_text="¿Ya se envió el recordatorio?"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que se envió el recordatorio",
                        null=True,
                    ),
                ),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_recordatorio",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Recordatorio",
                "verbose_name_plural": "Configuraciones de Recordatorios",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario_email",
                    models.EmailField(
                        help_text="Correo del destinatario", max_length=254
                    ),
                ),
                (
                    "destinatario_nombre",
                    models.CharField(
                        blank=True, help_text="Nombre del destinatario", max_length=200
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        help_text="Asunto del correo enviado", max_length=200
                    ),
                ),
                ("cuerpo", models.TextField(help_text="Cuerpo del correo enviado")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("ERROR", "Error"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha programada para envío",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, help_text="Fecha real de envío", null=True
                    ),
                ),
                (
                    "intentos",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de intentos de envío"
                    ),
                ),
                (
                    "error_mensaje",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si falló el envío"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="eventos.evento",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="inscripciones.inscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_programada"],
            },
        ),
    ]
