# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillacorreo",
            name="creada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantillacorreo",
            name="tipo_notificacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantillas",
                to="notificaciones.tiponotificacion",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="tipo_notificacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notificaciones",
                to="notificaciones.tiponotificacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantillacorreo",
            unique_together={("tipo_notificacion", "nombre")},
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["estado", "fecha_programada"],
                name="notificacio_estado_3dc4bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["destinatario_email"], name="notificacio_destina_62a9f2_idx"
            ),
        ),
    ]
