# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sesion",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de sesión del evento"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora del registro de asistencia",
                    ),
                ),
                (
                    "metodo_registro",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("QR", "Código QR"),
                            ("AUTOMATICO", "Automático"),
                        ],
                        default="MANUAL",
                        help_text="Método utilizado para registrar la asistencia",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se registró (para QR)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent del dispositivo (para QR)"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre la asistencia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="ControlAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sesion", models.PositiveIntegerField(help_text="Número de sesión")),
                (
                    "fecha_sesion",
                    models.DateTimeField(help_text="Fecha y hora de la sesión"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="¿El control de asistencia está activo?"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones sobre la sesión"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Control de Asistencia",
                "verbose_name_plural": "Controles de Asistencia",
                "ordering": ["evento", "sesion"],
            },
        ),
    ]
