# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificados", "0001_initial"),
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="inscripcion",
            field=models.OneToOneField(
                help_text="Inscripción asociada al certificado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificado",
                to="inscripciones.inscripcion",
            ),
        ),
    ]
