# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroMasivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_original",
                    models.FileField(
                        help_text="Archivo Excel/CSV original",
                        upload_to="inscripciones/masivos/%Y/%m/",
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_registros", models.PositiveIntegerField(default=0)),
                ("registros_exitosos", models.PositiveIntegerField(default=0)),
                ("registros_fallidos", models.PositiveIntegerField(default=0)),
                (
                    "reporte_errores",
                    models.TextField(
                        blank=True, help_text="Detalle de errores encontrados"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Masivo",
                "verbose_name_plural": "Registros Masivos",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del participante", max_length=100
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        help_text="Apellido del participante", max_length=100
                    ),
                ),
                (
                    "documento",
                    models.CharField(help_text="Número de documento", max_length=20),
                ),
                (
                    "correo",
                    models.EmailField(
                        help_text="Correo electrónico",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "telefono",
                    models.CharField(help_text="Teléfono de contacto", max_length=15),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        help_text="Estado de la inscripción",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de inscripción",
                    ),
                ),
                (
                    "codigo_qr",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Código único para QR de asistencia",
                        unique=True,
                    ),
                ),
                (
                    "pago_confirmado",
                    models.BooleanField(
                        default=False, help_text="¿El pago ha sido confirmado?"
                    ),
                ),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de confirmación de la inscripción",
                        null=True,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas o comentarios adicionales"
                    ),
                ),
                (
                    "registro_masivo",
                    models.BooleanField(
                        default=False,
                        help_text="¿Fue registrado mediante carga masiva?",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        help_text="Evento al que se inscribe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "ordering": ["-fecha_inscripcion"],
            },
        ),
    ]
