# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0002_initial"),
        ("inscripciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario registrado (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registromasivo",
            name="cargado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registromasivo",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_masivos",
                to="eventos.evento",
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcion",
            index=models.Index(
                fields=["evento", "estado"], name="inscripcion_evento__ea1862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcion",
            index=models.Index(
                fields=["codigo_qr"], name="inscripcion_codigo__76c36a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcion",
            index=models.Index(fields=["correo"], name="inscripcion_correo_950a56_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("evento", "documento")},
        ),
    ]
