# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPasarela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("PAYU", "PayU"),
                            ("WOMPI", "Wompi"),
                            ("STRIPE", "Stripe"),
                            ("MERCADOPAGO", "Mercado Pago"),
                        ],
                        help_text="Nombre de la pasarela",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=False, help_text="¿Esta pasarela está activa?"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="API Key / Secret Key", max_length=200
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        blank=True, help_text="Public Key / Client ID", max_length=200
                    ),
                ),
                (
                    "url_api",
                    models.URLField(
                        blank=True, help_text="URL de la API de la pasarela"
                    ),
                ),
                (
                    "modo_prueba",
                    models.BooleanField(
                        default=True, help_text="¿Está en modo de prueba?"
                    ),
                ),
                (
                    "configuracion_adicional",
                    models.JSONField(
                        blank=True,
                        help_text="Configuración adicional en formato JSON",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Pasarela",
                "verbose_name_plural": "Configuraciones de Pasarelas",
            },
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia Bancaria"),
                            ("TARJETA", "Tarjeta de Crédito/Débito"),
                            ("PASARELA", "Pasarela de Pagos"),
                        ],
                        help_text="Código del método de pago",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del método de pago", max_length=100
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripción del método"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="¿Este método está activo?"
                    ),
                ),
                (
                    "requiere_comprobante",
                    models.BooleanField(
                        default=False, help_text="¿Requiere adjuntar comprobante?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Pago",
                "verbose_name_plural": "Métodos de Pago",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto del pago",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia o transacción",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("RECHAZADO", "Rechazado"),
                            ("REEMBOLSADO", "Reembolsado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        help_text="Estado del pago",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha del pago"
                    ),
                ),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de confirmación del pago",
                        null=True,
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        help_text="Comprobante de pago (imagen o PDF)",
                        null=True,
                        upload_to="pagos/comprobantes/%Y/%m/",
                    ),
                ),
                (
                    "pasarela_transaccion_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de transacción de la pasarela",
                        max_length=200,
                    ),
                ),
                (
                    "pasarela_respuesta",
                    models.TextField(
                        blank=True, help_text="Respuesta completa de la pasarela (JSON)"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre el pago"
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        help_text="Inscripción asociada al pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="inscripciones.inscripcion",
                    ),
                ),
                (
                    "metodo_pago",
                    models.ForeignKey(
                        help_text="Método de pago utilizado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="pagos.metodopago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
