# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que registró el pago (si es manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["inscripcion", "estado"], name="pagos_pago_inscrip_e77bde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["referencia"], name="pagos_pago_referen_424544_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["pasarela_transaccion_id"], name="pagos_pago_pasarel_cd7a31_idx"
            ),
        ),
    ]
