# Generated by Django 5.2.7 on 2025-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracionPasarela",
        ),
        migrations.AlterField(
            model_name="metodopago",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TRANSFERENCIA", "Transferencia Bancaria"),
                    ("TARJETA", "Tarjeta de Crédito/Débito"),
                ],
                help_text="Código del método de pago",
                max_length=20,
                unique=True,
            ),
        ),
    ]
