# Generated by Django 5.2.7 on 2025-11-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asistencias", "0002_initial"),
        ("eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que registró la asistencia (si es manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_registradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controlasistencia",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controlasistencia",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles_asistencia",
                to="eventos.evento",
            ),
        ),
        migrations.AddIndex(
            model_name="asistencia",
            index=models.Index(
                fields=["inscripcion", "sesion"], name="asistencias_inscrip_0a3f51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asistencia",
            index=models.Index(
                fields=["fecha_registro"], name="asistencias_fecha_r_c26e29_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together={("inscripcion", "sesion")},
        ),
        migrations.AlterUniqueTogether(
            name="controlasistencia",
            unique_together={("evento", "sesion")},
        ),
    ]
